name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule: # Every Melbourne midnight
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tlan16/docker-executable-fdroidserver:latest
          cache-from: type=registry,ref=ghcr.io/tlan16/docker-executable-fdroidserver:latest
          cache-to: type=inline
