name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule: # Every Melbourne midnight
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/tlan16/docker-executable-fdroidserver:latest
          cache-from: type=registry,ref=ghcr.io/tlan16/docker-executable-fdroidserver:latest
          cache-to: type=inline
      - uses: gautamkrishnar/keepalive-workflow@1.1.0
