name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "ghcr.io/tlan16/docker-executable-fdroidserver:latest"
    - name: Authenticate to Github Docker
      run: docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image to GitHub
      run: docker push "ghcr.io/tlan16/docker-executable-fdroidserver:latest"
